### ISSUE TITLE
can't install on node v5.3.0

### ISSUE THREAD

**Issue by chovy** [onmodulus/process-monitor#6]
When I run `npm install process-monitor -S` I get this error on mac 

```
  CXX(target) Release/obj.target/sysinfo/src/binding.o
../src/binding.cpp:17:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("OS"), String::New(OS));
                ~~~~~~~~^
../src/binding.cpp:17:50: error: no member named 'New' in 'v8::String'
    target->Set(String::NewSymbol("OS"), String::New(OS));
                                         ~~~~~~~~^
2 errors generated.
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/username/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Users/username/.nvm/versions/node/v5.3.0/bin/node" "/Users/username/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/projects/chovy/torula/torula-scraper/node_modules/usage
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPEERINVALID cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/username/.nvm/versions/node/v5.3.0/bin/node" "/Users/username/.nvm/versions/node/v5.3.0/bin/npm" "install" "process-monitor" "-S"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! usage@0.3.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usage@0.3.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/username/projects/chovy/torula/torula-scraper/npm-debug.log
```

**Comment by danieljoppi** [comment]
test this fork: https://github.com/pankyka/process-monitor

**Comment by tzmanics** [comment]
Hi @chovy sorry for the delay. Thanks for your response @danieljoppi.
@chovy did this help shed some light on your issue? I'm going to close this issue but if you still need assistance please feel free to open it back up!

Thanks!

**Comment by achavva** [comment]
I am facing the same issue, how to resolve it
